[Settings]
# Face detection parameters
FACE_SCALE_FACTOR = 1.1
FACE_MIN_NEIGHBOURS = 5
SMILE_SCALE_FACTOR = 1.7
SMILE_MIN_NEIGHBOURS = 22
TIME_TO_START_COUNTING = 3.0
LANGUAGE = en

[Font]
font = HERSHEY_SIMPLEX
scale = 1
color = (255, 0, 0)
thickness = 3
line_type = 2