[Settings]
# Face detection parameters
FACE_SCALE_FACTOR = 1.1        ; Scale factor for face detection
FACE_MIN_NEIGHBOURS = 5        ; Minimum neighbors for face detection
SMILE_SCALE_FACTOR = 1.7       ; Scale factor for smile detection
SMILE_MIN_NEIGHBOURS = 22      ; Minimum neighbors for smile detection
TIME_TO_START_COUNTING = 3.0   ; Time delay before counting
LANGUAGE = en                  ; Default language

[Font]
font = HERSHEY_SIMPLEX
scale = 1
color = (255, 0, 0)
thickness = 3
line_type = 2